### ISSUE TITLE
CAD Train scripts on COCO

### ISSUE THREAD

**Issue by adambielski** [valeoai/LOST#10]
Is it possible to share the scripts/config to train CAD on COCO? There's only one for VOC in the repo.
Thanks

**Comment by osimeoni** [comment]
Hi @adambielski, thanks for your interest. I will share those in the next days.

**Comment by osimeoni** [comment]
Hi @adambielski, I have added a **Training LOST+CAD on COCO20k dataset** section. 
Hope that helps ! 
Oriane

**Comment by adambielski** [comment]
@osimeoni Thanks a lot! In the end I managed to run it on my own, but now I can compare if everything I did was correct.
