### ISSUE TITLE
Multi-object discovery

### ISSUE THREAD

**Issue by rgbd-zml** [valeoai/LOST#11]
HI, I have a confusion about the interesting work.
How to perform multi-target discovery in the figure 1 (middle) of your paper？
Any advice is greatly appreciated.

**Comment by osimeoni** [comment]
Hi @rgbd-zml, 
Thank you for your interest. 
Our method LOST discovers one object per image. However, we subsequently train a detector in a fully-supervised fashion using the detections of LOST as pseudo ground-truth. Doing so we obtain a detector that outputs several predictions per image, which was used to obtain the middle figure in Figure 1 of our paper. I hope this helps!
