### ISSUE TITLE
Can do multiple object localize only by LOST?

### ISSUE THREAD

**Issue by BENULL** [valeoai/LOST#13]

**Comment by Yanghao-Wang** [comment]
I have the same question. Have you find out?

**Comment by osimeoni** [comment]
Dear both, thank you for your interest. 

LOST by itself is designed to discover a single object per image. But we additionally propose to train a simple class-agnostic detector (named CAD) with LOST predictions as pseudo-boxes which at inference produce multi-objects predictions. Please see the section `Towards unsupervised object detection`

Hope that helps !
