### ISSUE TITLE
Class-aware detection

### ISSUE THREAD

**Issue by gholste** [valeoai/LOST#4]
Do you plan on releasing code for class-aware detection (i.e., to produce the results in Table 3 of https://arxiv.org/pdf/2109.14279.pdf)? I don't believe I see any of the necessary code for assigning object categories to boxes, but please correct me if I'm wrong.

**Comment by osimeoni** [comment]
Hi @gholste, thanks for you interest. We will release LOST + OD in the following days.

**Comment by gholste** [comment]
Awesome! Looking forward to it.
