### ISSUE TITLE
Pretrained model of CAD model

### ISSUE THREAD

**Issue by Mirsadeghi** [valeoai/LOST#6]
Dear @osimeoni. 
Could you release your trained Class-Agnostic Detector (CAD) models?
Thanks

**Comment by osimeoni** [comment]
Dear @Mirsadeghi, 
Sorry for the late answer. I will share the model with you in the next days.

**Comment by Mirsadeghi** [comment]
Thank you @osimeoni.

**Comment by osimeoni** [comment]
Dear @Mirsadeghi, please find models in `https://github.com/valeoai/LOST/releases`.
