### ISSUE TITLE
Error in evaluation with Detectron2

### ISSUE THREAD

**Issue by MarcVisions** [valeoai/LOST#7]
Hi @osimeoni,

Thank you for making the code available!

When evaluating Detectron2 on VOC12 with the obtained pseudolables. I obtain the following error: 
AttributeError: "int object has no attribute 'value'. It seems that the coco_style_file is not registered by 'register_coco_instances' (see image underneath). Any idea how this can be fixed? Thanks.

![image](https://user-images.githubusercontent.com/100088451/154855805-57acb732-eb5c-49d6-b059-b42a5fefb209.png)

**Comment by MarcVisions** [comment]
It seems that the BoxMode causes the error. The data in the generated dictionary for the training/evaluation uses "0" as the BoxMode but this should be mapped again to `BoxMode.XYXY_ABS` in Detectron2. Detectron2 can not handle 0. I believe it would be better to use the "load_coco_json" function in `detectron2/data/dataset/coco.py`.

**Comment by osimeoni** [comment]
Hi @MarcVisions, 

Could you please share your entire error logs? The screenshot appears to be cut before the error is raised. 
Also could you please give me details on how to reproduce your error?
