### ISSUE TITLE
corLoc evaluation

### ISSUE THREAD

**Issue by Mirsadeghi** [valeoai/LOST#8]
Hi @osimeoni . I am suspicious about the corLoc evaluation part in the code. The corLoc for each image is true whenever one of the ground truth objects is hit! https://github.com/valeoai/LOST/blob/2b678aca89c18aa79c56ec3f6d4a0b979a91608d/main_lost.py#L311
What about other objects? Is it right?

**Comment by osimeoni** [comment]
Hi @Mirsadeghi, 

The corloc metric is designed for one **single** prediction per image. It is used to measure if the predicted bounding box corresponds to any of the objects in the image as we wrote in the paper: 

`Correct Localization (CorLoc) metric, i.e., the percentage of correct boxes, where a predicted box is considered correct if it has an intersection over union (IoU) score superior to 0.5 with one of the labeled object bounding boxes.
`

The code is therefore correct and I am closing this issue. Let me know if it is not clear still.
